### ISSUE TITLE
Calendar UI Buttons

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#10]
We need  both a close button, to hide the calendar UI (go back to the <datepicker> element)

and a submit button to submit the chosen dates (go back to the <datepicker> element reflecting the chosen dates.)

**Comment by tyagiakash926** [comment]
@ctrachte assign it to me i am intersting to give u small efforts of mine in Your project.

**Comment by tyagiakash926** [comment]
it is compulsory to ceate new branch , i can do changes in master branch also?
