### ISSUE TITLE
Left and Right Arrows on Calendar

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#11]
They should exist on either side of the monthHeader, example: < November >
Clicking arrows will advance the month and redraw the calendar.

**Comment by tyagiakash926** [comment]
@ctrachte hey assign it to me. I can do it

**Comment by ctrachte** [comment]
@tyagiakash926 this task is currently in progress already. check out the projects tab to keep up-to-date

**Comment by opethrocks** [comment]
I was able to add the arrows but I'm unsure on the logic required to actually change the month. I'm also unsure if this issue has been assigned to me.

**Comment by ctrachte** [comment]
@opethrocks thanks for looking into it, however this issue is already in progress and will be merged to the master branch soon. Please checkout the Projects tab to see what is currently in progress, and if you would like to pick something in-progress please comment on that issue instead.
