### ISSUE TITLE
Make styling accessible, contrasting, "TEAM-friendly"

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#12]
adjustments must be made to the JS/CSS to make all colors and shading appropriate for TEAM integration, and accessible to all users (eg. high contrast so it's visible/legible at any size).

**Comment by alesandrog** [comment]
Hi there! I would like to help with this one.

**Comment by ctrachte** [comment]
Ok sure, please be sure to follow our contribution steps detailed in the readme.

**Comment by ctrachte** [comment]
Please also add all accessibility properties  (for example, "aria-labeled-by")

**Comment by ctrachte** [comment]
I have merged this branch with the master and resolved all conflicts. 

I will not be closing this issue (#28, #12) because we will need to be constantly adding accessibility features as the API and it's functionality grows.
