### ISSUE TITLE
Calendar Placement, Responsiveness

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#146]
Currently, when using the Datepicker on smaller devices, the calendar will not be entirely visible on the screen because of absolute placement. 

We need to rework the calendar placement so that: 

*Smaller devices don't bother with `datepicker.calendarPlacement()` but rather use straight css, and breakpoints*
- Calendar should be 100% width and centered for small devices, not a static size. Add this to the CSS. 
- Add logic to `datepicker.calendarPlacement()` method to detect screen size and disable if a small screen size. (galaxy s5 for example), or mobile device. Calendar then relies solely on CSS and media breakpoint queries that correspond with this logic. 
- Calendar placement method `datepicker.calendarPlacement()`  should still exist for larger screens such as desktop monitors, etc.

**Comment by himansh-gjr** [comment]
Thanks !
it's working now, issue was  the <script> tag that referenced  `Datepicker.js`  file in Datepicker.html was commented at line no 7
then by uncommenting it, it worked !
<img width="696" alt="Screenshot 2021-10-19 at 11 57 52 PM" src="https://user-images.githubusercontent.com/77732259/137969724-997797d9-0fe8-413c-b6f6-d6b2e4a37657.png">

**Comment by ctrachte** [comment]
Yes that should work! Anything above 768 should be using the static width calendar, and `.calendarPlacement()` method.
