### ISSUE TITLE
Needs time picker

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#2]
start/end time which will be coordinated with start/end date

**Comment by ctrachte** [comment]
This will need to be turned on/off Programmatically, so the element must exist on the calendar element, but be modular such that it can be hidden.

**Comment by ctrachte** [comment]
Time picker needs to be much easier to use/see when it's required. Current version its very tedious to pick the exact hour you need.

**Comment by MrRedBeard** [comment]
Working on a solution for this

**Comment by MrRedBeard** [comment]
What will the default times be? start 8am end 9am?

**Comment by MrRedBeard** [comment]
Also the bottom 2 columns are not even. Do you want me to fix this with this issue?

**Comment by ctrachte** [comment]
bottom two columns we can worry about later. Start times should probably be 12pm - 1pm (middle of the day) or maybe 12 hours apart (12pm - 12am). 

Not a big deal if you've already committed, it can always be adjusted later.

**Comment by ctrachte** [comment]
by the way, just make the time picker adjustable via the "arrows" for now, I plan to make another task/issue to make all the dates/times adjustable via user input fields.

**Comment by MrRedBeard** [comment]
I made a pull request but it did not like it. I can provide changes separately or delete my fork and reimplement the changes.

**Comment by MrRedBeard** [comment]
Got it resolved it was a stupid conflict
