### ISSUE TITLE
Dynamic CSS Color Palette

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#39]
We need the primary, secondary tertiary colors to be made dynamic in the CSS file so that developers can easily switch them without breaking the entire stylesheet.

**Example:**

```
:root {
  --color-blue: #1e90ff; /* hex value for dodgerblue color */
}

.element {
  background: var(--color-blue);
}

```

**Comment by andrewdeclue** [comment]
I have some colors

**Comment by ctrachte** [comment]
Please do share said colors @andrewdeclue
