### ISSUE TITLE
AutoClose - True/False

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#9]
If options.autoclose = true

=> close the Calendar UI after picking the proper single date, or start/end dates.

if options.autoclose = false 

=> close the Calendar UI only when 'close' button is clicked

**Comment by MrRedBeard** [comment]
Working on the initial AutoClose functionality. A placeholder for the element needs to be added so that the calendar can be accessed after the calendar is closed.

**Comment by ctrachte** [comment]
Ok I will review today, and likely merge. Thanks for working on this. I have assigned it to you and move the task to the "review" column.

**Comment by ctrachte** [comment]
By the way, Andrew was supposed to be working on the "placeholder" element you're talking about. It's currently assigned to him, but I do not know if he's made any progress.

**Comment by MrRedBeard** [comment]
I saw that after the fact
