### ISSUE TITLE
Start/End Label in modal

### ISSUE THREAD

**Issue by tabasaki** [ctrachte/Datepicker.js#90]
I changed the html settings for auto close true, and time picker off.
When the modal opens the start and end date both say Event End...but once you select values they change to Start and End.
Not a major thing at all just something I noticed.
Also, when you select the first value it loads in its placeholder but the end shows as --/--/---- undefined. Can we lose the undefined there. Again nothing major, just aesthetics

**Comment by ctrachte** [comment]
Thanks, I will work to recreate this and fix it.

**Comment by ctrachte** [comment]
This is probably an edge case in the custom label logic that isnt handled.
