### ISSUE TITLE
Remove `onSubmit()` validation checks

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/Datepicker.js#99]
From user Matt: 

*"I am trying to set an array of dates based on the start and end date when the submit button is clicked. Right now, the onSubmit closes the modal still, but doesn't work when they pick one date."*

ToDo:
- Remove validation check that only fires `onSubmit` if the user has chosen 2 dates (range picker) or one date (single date).

**Comment by albertrzcinski** [comment]
I would like to tackle this issue. Let me know if you still need help.

**Comment by ctrachte** [comment]
I have assigned this to you @albertrzcinski . Please create a new branch on your own cloned copy, track your work on the progress board, and submit a pull request for review upon completion.
